routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'ComunidadController@index')->name('index');

Route::get('/comunidades','ComunidadController@getComunidades');

Route::get('/provincias/{id}','ProvinciaController@getProvincias');
Route::get('register/provincias/{id}','ProvinciaController@getProvincias');

Route::get('/municipios/{id}','MunicipioController@getMunicipios');
Route::get('register/municipios/{id}','MunicipioController@getMunicipios');

Route::get('/mapa/recogerForm','MapaController@recogerForm');

Route::post('/mapa/recogerForm','MapaController@recogerForm');
Route::get('/mapa', 'MapaController@viewLocations');

Route::get('/procesar/{id}','MapaProcesarController@procesarPeticion');



Route::get('/home', 'HomeController@index')->name('home');

Route::get('/blog', 'PagesController@home')->name('blog.show');

Route::get('blog/{post}','PostsController@show')->name('posts.show');
Route::get('categorias/{category}','CategoriesController@show')->name('categories.show');
Route::get('tags/{tag}','TagsController@show')->name('tags.show');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin','middleware' => 'auth'],function(){

    Route::resource('posts', 'PostController',['except' => 'show', 'as' => 'admin']);
    Route::resource('users', 'UsersController',['as' => 'admin']);

    Route::put('users/{user}/roles', 'UsersRolesController@update')->name('admin.users.roles.update');
    Route::put('users/{user}/permissions', 'UsersPermissionsController@update')->name('admin.users.permissions.update');

    // Route::get('posts','PostController@index')->name('admin.posts.index');
    // Route::get('posts/create','PostController@create')->name('admin.posts.create');
    // Route::post('posts','PostController@store')->name('admin.posts.store');
    // Route::get('posts/{post}','PostController@edit')->name('admin.posts.edit');
    // Route::put('posts/{post}','PostController@update')->name('admin.posts.update');
    // Route::delete('posts/{post}', 'PostController@destroy')->name('admin.posts.destroy');


    Route::get('/','AdminController@index')->name('dashboard');

    Route::get('escrito','EscritController@index')->name('admin.escrito.index');
    Route::get('escrito/create','EscritController@create')->name('admin.escrito.create');

    Route::post('posts/{post}/photos','PhotosController@store')->name('admin.post.photos.update');
    Route::delete('photos/{photo}','PhotosController@destroy')->name('admin.photos.destroy');
});




Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

app/User.php
<?php

namespace App;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Post;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'surname1', 'surname2', 'comunidad_id', 'provincia_id', 'municipio_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\UpdateUserRequest;
use Illuminate\Support\Str;
use App\Comunidad;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('admin.users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User;
        $comunidades = Comunidad::all();
        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name','id');

        return view('admin.users.create',compact('user','roles','permissions','comunidades'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $pos = strpos($request['cbx_municipio'], '{');
        $municipio = substr($request['cbx_municipio'], 0, $pos);
            
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'surname1' => ['required', 'string'],
            'surname2' => ['required', 'string'],
            'cbx_comunidad' => ['required'],
            'cbx_provincia' => ['required'],
            'cbx_municipio' => ['required'],
        ]);

        
        $data['password'] = Str::random(8);

        $user = User::create([
            'name' => $data['name'],
            'email' =>$data['email'],
            'password' => $data['password'],
            'surname1' => $data['surname1'],
            'surname2' => $data['surname2'],                        
            'comunidad_id' => $data['cbx_comunidad'],
            'provincia_id' => $data['cbx_provincia'],  
            'municipio_id' => $municipio,
            
        ]);

        $user->assignRole($request->roles);

        $user->givePermissionTo($request->permissions);

        return redirect()->route('admin.users.index')->withFlash('El usuario ha sido creado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //$roles = Role::pluck('name','id');

        $comunidades = Comunidad::all();
        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name','id');

        return view('admin.users.edit',compact('user','roles','permissions','comunidades'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $user->update($request->validated());
        
        return back()->withFlash('Usuario actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Datos Personales</h3>
        </div>
        <div class="card-body">
            @if ($errors->any())
            <ul class="list-group">
                @foreach ($errors->all() as $error)
                <li class="list-group-item list-group-item-danger">{{ $error }}</li>
                @endforeach
            </ul>
            @endif

            <form method="POST" action=" {{ route('admin.users.store') }}">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name">Nombre:</label>
                    <input name="name" value="{{ old('name') }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="surname1"> Primer Apellido
                    </label>


                    <input id="surname1" type="text" class="form-control @error('surname1') is-invalid @enderror"
                        name="surname1" value="{{ old('surname1') }}" required autocomplete="name" autofocus>

                    @error('surname1')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="surname2">Segundo Apellido</label>


                    <input id="surname2" type="text" class="form-control @error('surname2') is-invalid @enderror"
                        name="surname2" value="{{ old('surname2') }}" required autocomplete="name" autofocus>

                    @error('surname2')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>



                <div class="form-group">
                    <label for="cbx_comunidad">Seleccione
                        Comunidad:</label>

                    <select class="form-control @error('cbx_comunidad') is-invalid @enderror" name="cbx_comunidad"
                        id="cbx_comunidad" required>
             
                    </select>

                    @error('cbx_comunidad')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="cbx_provincia">Seleccione
                        Provincia:</label>


                    <select class="form-control @error('cbx_provincia') is-invalid @enderror" name="cbx_provincia"
                        id="cbx_provincia" required>

                    </select>

                    @error('cbx_provincia')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
      
        <div class="form-group">
            <label for="municipio">Seleccione
                Municipio:</label>


            <select class="form-control @error('cbx_municipio') is-invalid @enderror" name="cbx_municipio"
                id="cbx_municipio" required>
                <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />

                <input id="longitud" name="longitud" type="hidden" value="">
                <input id="latitud" name="latitud" type="hidden" value="">

            </select>

            @error('cbx_municipio')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input name="email" value="{{ old('email') }}" class="form-control">
        </div>

        <div class="form-group">
            <label>Roles</label>
            @include('admin.roles.checkboxes')
        </div>

        <div class="form-group">
            <label>Permisos</label>
            @include('admin.permissions.checkboxes')
        </div>
        <span class="help-block">La contraseña será generada y enviada al usuario vía email</span><br><br>
        <button class="btn btn-primary btn-block">Crear usuario</button>
        </form>
    </div>

</div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
    <div class="col-md-6">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">Datos Personales</h3>
            </div>
            <div class="card-body">
                @if ($errors->any())
                <ul class="list-group">
                    @foreach ($errors->all() as $error)
                    <li class="list-group-item list-group-item-danger">{{ $error }}</li>
                    @endforeach
                </ul>
                @endif

                <form method="POST" action=" {{ route('admin.users.update', $user) }}">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="form-group">
                        <label for="name">Nombre:</label>
                        <input name="name" value="{{ old('name',$user->name) }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="surname1"> Primer Apellido
                        </label>


                        <input id="surname1" type="text" class="form-control @error('surname1') is-invalid @enderror"
                            name="surname1" value="{{ old('surname1',$user->surname1) }}" required autocomplete="name" autofocus>

                        @error('surname1')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>


                    <div class="form-group">
                        <label for="surname2">Segundo Apellido</label>


                        <input id="surname2" type="text" class="form-control @error('surname2') is-invalid @enderror"
                            name="surname2" value="{{ old('surname2',$user->surname2) }}" required autocomplete="name" autofocus>

                        @error('surname2')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>



                    <div class="form-group">
                        <label for="cbx_comunidad">Seleccione
                            Comunidad:</label>                               
                        <select data-id="{{ $user->comunidad_id ?: '' }}" class="form-control @error('cbx_comunidad') is-invalid @enderror" name="cbx_comunidad"
                            id="cbx_comunidad" required>
                        </select>

                        @error('cbx_comunidad')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>


                    <div class="form-group">
                        <label for="cbx_provincia">Seleccione
                            Provincia:</label>


                        <select data-id="{{ $user->provincia_id ?: '' }}" class="form-control @error('cbx_provincia') is-invalid @enderror" name="cbx_provincia"
                            id="cbx_provincia" required>

                        </select>

                        @error('cbx_provincia')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="municipio">Seleccione
                            Municipio:</label>


                        <select data-id="{{ $user->municipio_id ?: '' }}" class="form-control @error('cbx_municipio') is-invalid @enderror" name="cbx_municipio"
                            id="cbx_municipio" required>
                            <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />

                            <input id="longitud" name="longitud" type="hidden" value="">
                            <input id="latitud" name="latitud" type="hidden" value="">

                        </select>

                        @error('cbx_municipio')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input name="email" value="{{ old('email',$user->email) }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Contraseña:</label>
                        <input type="password" name="password" placeholder="Contraseña" class="form-control">
                        <span class="help-block">Dejar en blanco para no cambiar la contraseña</span>
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">Repite la contraseña:</label>
                        <input type="password" name="password_confirmation" placeholder="Repite la contraseña"
                            class="form-control">

                    </div>
                    <div class="form-group">
                        <label>Roles</label>
                        @include('admin.roles.checkboxes')
                    </div>

                    <div class="form-group">
                        <label>Permisos</label>
                        @include('admin.permissions.checkboxes')
                    </div>

        
                    <button class="btn btn-primary btn-block">Actualizar usuario</button>
                </form>
            </div>

        </div>
    </div>
    <div class="col-md-6">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">Roles</h3>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('admin.users.roles.update', $user) }}">
                    {{ csrf_field() }} {{ method_field('PUT') }}
                    @include('admin.roles.checkboxes')
                    <button class="btn btn-primary btn-block">Actualizar roles</button>
                </form>
            </div>
        </div>

        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">Permisos</h3>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('admin.users.permissions.update', $user) }}">
                    {{ csrf_field() }} {{ method_field('PUT') }}
                    @include('admin.permissions.checkboxes')
                    <button class="btn btn-primary btn-block">Actualizar permisos</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layout')

@section('header')
<div class="col-sm-12">
    <h1 class="m-0 text-dark">Todo los usuarios</h1>

</div><!-- /.col -->
<div class="col-sm-12">
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Inicio</a></li>
        <li class="breadcrumb-item active"><a href="{{ route('admin.users.index') }}">Usuarios</a></li>
    </ol>
</div><!-- /.col -->
<div class="col-sm-12">
    <a href="{{ route('admin.users.create') }}" class="btn btn-primary float-right">
        <i class="fa fa-plus">Crear usuarios</i>
    </a>
</div>

@endsection

@section('content')

<div class="col-md-12">

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Todos los usuarios</h3>
        </div>

        <div class="card-body">
            <table id="users-table" class="display responsive nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Email</th>
                        <th>Roles</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email}}</td>
                        <td>{{ $user->getRoleNames()->implode(',') }}</td>
                        <td>
                            <a href="{{ route('admin.users.show', $user )}}" class="btn btn-xs btn-light"><i
                                    class="fa fa-eye"></i></a>
                            <a href="{{ route('admin.users.edit', $user )}}" class="btn btn-xs btn-info"><i
                                    class="fa fa-magic"></i></a>
                            <form method="POST" action="{{ route('admin.users.destroy',$user) }}"
                                style="display: inline">
                                {{ csrf_field() }} {{ method_field('DELETE') }}
                                <button class="btn btn-xs btn-danger"
                                    onclick="return confirm('¿Estás seguro de eliminar este usuario?')"><i
                                        class="fa fa-times"></i></button>
                            </form>


                        </td>
                    </tr>
                    @endforeach
                </tbody>

            </table>

        </div>
        <!-- </div> -->
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
    aria-hidden="true">
    <form method="POST" action="{{ route('admin.users.store') }}">
        {{ csrf_field() }}

        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Introduce el título de la usuario</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="form-control @error('title') is-invalid @enderror">Título del
                            usuario</label>
                        <input name="title" value="{{ old('title') }}" class="form-control"
                            placeholder="introduce el título de la usuario">

                        {!! $errors->first('title','<span class="help-block text-danger">:message</span>') !!}

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button class="btn btn-primary">Crear usuario</button>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/admin/users/show.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
    <div class="col-md-3">
        <!-- Profile Image -->
        <div class="card card-primary card-outline">
            <div class="card-body box-profile">
                <div class="text-center">
                    <img class="profile-user-img img-fluid img-circle" src="/adminlte/img/user4-128x128.jpg"
                        alt="{{ $user->name }}">
                </div>

                <h3 class="profile-username text-center">{{ $user->name }}</h3>

                <p class="text-muted text-center">{{ $user->getRoleNames()->implode(', ') }}</p>

                <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                        <b>Email</b> <a class="float-right">{{ $user->email }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Publicaciones</b> <a class="float-right">{{ $user->posts->count() }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Roles</b> <a class="float-right">{{ $user->getRoleNames()->implode(', ') }}</a>
                    </li>
                </ul>

                <a href="#" class="btn btn-primary btn-block"><b>Editar</b></a>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
    <!-- /.card -->
    <div class="col-md-3">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">Publicaciones</h3>
            </div>
            <div class="card-body">
                @forelse ($user->posts as $post)
                <a href="{{ route('posts.show', $post) }}" target="_blank"><strong>{{ $post->title }}</strong>
                </a>
                <br>
                <small class="text-muted">Publicado el {{ $post->published_at->format('d/M/Y') }}</small>
                <p class="text-muted">{{ $post->excerpt }}</p>
                @unless($loop->last)
                <hr>
                @endunless
                @empty
                <small class="text-muted">No tiene ninguna publicación</small>
                @endforelse
            </div>

        </div>
    </div>
    <div class="col-md-3">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">Roles</h3>
            </div>
            <div class="card-body">
                @forelse ($user->roles as $role)
                <strong>{{ $role->name }}</strong>
                @if($role->permissions->count())
                <br>
                <small class="text-muted">Permisos: {{ $role->permissions->pluck('name')->implode(', ') }}</small>
                @endif
                @unless($loop->last)
                <hr>
                @endunless

                @empty
                <small class="text-muted">No tiene ningún role asociado</small>
                @endforelse
            </div>

        </div>
    </div>
    <div class="col-md-3">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">Permisos adicionales</h3>
            </div>
            <div class="card-body">
                @forelse ($user->permissions as $permission)
                <strong>{{ $permission->name }}</strong>

                @unless($loop->last)
                <hr>
                @endunless

                @empty
                <small class="text-muted">No tiene permisos adicionales</small>
                @endforelse
            </div>

        </div>
    </div>
</div>

@endsection