routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'ComunidadController@index')->name('index');

Route::get('/comunidades','ComunidadController@getComunidades');

Route::get('/provincias/{id}','ProvinciaController@getProvincias');
Route::get('register/provincias/{id}','ProvinciaController@getProvincias');

Route::get('/municipios/{id}','MunicipioController@getMunicipios');
Route::get('register/municipios/{id}','MunicipioController@getMunicipios');

Route::get('/mapa/recogerForm','MapaController@recogerForm');

Route::post('/mapa/recogerForm','MapaController@recogerForm');
Route::get('/mapa', 'MapaController@viewLocations');

Route::get('/procesar/{id}','MapaProcesarController@procesarPeticion');



Route::get('/home', 'HomeController@index')->name('home');

Route::get('/blog', 'PagesController@home')->name('blog.show');

Route::get('blog/{post}','PostsController@show')->name('posts.show');
Route::get('categorias/{category}','CategoriesController@show')->name('categories.show');
Route::get('tags/{tag}','TagsController@show')->name('tags.show');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin','middleware' => 'auth'],function(){

    Route::resource('posts', 'PostController',['except' => 'show', 'as' => 'admin']);
    Route::resource('users', 'UsersController',['as' => 'admin']);

    Route::put('users/{user}/roles', 'UsersRolesController@update')->name('admin.users.roles.update');
    Route::put('users/{user}/permissions', 'UsersPermissionsController@update')->name('admin.users.permissions.update');

    // Route::get('posts','PostController@index')->name('admin.posts.index');
    // Route::get('posts/create','PostController@create')->name('admin.posts.create');
    // Route::post('posts','PostController@store')->name('admin.posts.store');
    // Route::get('posts/{post}','PostController@edit')->name('admin.posts.edit');
    // Route::put('posts/{post}','PostController@update')->name('admin.posts.update');
    // Route::delete('posts/{post}', 'PostController@destroy')->name('admin.posts.destroy');


    Route::get('/','AdminController@index')->name('dashboard');

    Route::get('escrito','EscritController@index')->name('admin.escrito.index');
    Route::get('escrito/create','EscritController@create')->name('admin.escrito.create');

    Route::post('posts/{post}/photos','PhotosController@store')->name('admin.post.photos.update');
    Route::delete('photos/{photo}','PhotosController@destroy')->name('admin.photos.destroy');
});




Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

resources/views/admin/partial/footerBuyWithMe.blade.php
<div class="row miFondoPie">
                <div class="col12 col-sm-12 col-md-4">
                    <ul class="linksFooter">
                        <li><a href="#">Asesores & Precios</a></li>
                        <li><a href="#">Publica una asesoria</a></li>
                        <li><a href="#">Compartir día de compra</a></li>
                           
                    </ul>
                </div>
                <div class="col12 col-sm-12 col-md-4">
                        <ul class="linksFooter">
                            <li><a href="#">Sobre nosotros</a></li> 
                            <li><a href="#">Preguntas frecuentes</a></li>
                            <li><a href="#">Blog</a></li>
                     
                        </ul>
                </div>
                <div class="col12 col-sm-12 col-md-4">
                        <ul class="linksFooter">                            
                            <li><a href="#">Contacto</a></li>
                            <li><a href="#">Términos y condiciones</a></li> 
                            <li>BuyWithMe 2019 &copy;</li>
                        </ul>
                </div>
      
</div>
            
            
<div class="row pie">                
            <div class="col-12 d-flex flex-column justify-content-center col-sm-12 d-flex flex-sm-column justify-content-sm-center col-md-4 d-flex flex-md-row justify-content-md-start">
                <a href="{{route('index')}}" class="btn btn-info" >Inicio</a>
                <a href="{{route('blog.show')}}" class="btn btn-info">Blog</a>
                <a href="#" class="btn btn-info" >Contacto</a>
            </div>
            <div class="col-12 d-flex justify-content-center col-md-8 d-flex justify-content-md-end">
                <a href="nav-link"><i class="fa fa-facebook fa-2x"></i></a>
                <a href="nav-link"><i class="fa fa-twitter fa-2x"></i></a>
                <a href="nav-link"><i class="fa fa-linkedin fa-2x"></i></a>
                <a href="nav-link"><i class="fa fa-youtube fa-2x"></i></a>
                <a href="nav-link"><i class="fa fa-instagram fa-2x"></i></a>             
            </div>

</div>

resources/views/admin/partial/nav.blade.php
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
           <li class="nav-item">            
            <a href="{{ route('dashboard') }}" class="nav-link">Inicio
              <i class="nav-icon fas fa-home"></i>
              <p>

              </p>
            </a>
          </li>
          <li class="nav-item">            
            <a href="{{ route('admin.posts.index') }}" class="nav-link">Ver Posts
              <i class="nav-icon fas fa-eye"></i>
              <p>

              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" data-toggle="modal" data-target="#exampleModalLong" class="nav-link">Crear Post
              <i class="nav-icon fas fa-th"></i>
              <p>

              </p>
            </a>
          </li>
          <li class="nav-item">            
            <a href="{{ route('admin.users.index') }}" class="nav-link">Ver Usarios
              <i class="nav-icon fas fa-eye"></i>
              <p>

              </p>
            </a>
          </li>
          <li class="nav-item">            
            <a href="{{ route('admin.users.create') }}" class="nav-link">Crear usuario
              <i class="nav-icon fas fa-th"></i>
              <p>

              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('admin.escrito.index') }}" class="nav-link">Crear Escrito
              <i class="nav-icon fas fa-th"></i>
              <p>

              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->

resources/views/admin/partial/navBuyWithMe.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a href="{{ route('index') }}"><img class="miLogo" src="/imagenes/logo.png"></a>
    <a class="navbar-brand" href="{{ route('index') }}">BuyWithMe</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ Request::is('/') ? 'active' : '' }}">
                <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {{ Request::is('blog') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('blog.show') }}">Blog</a>
            </li>
            <li class="nav-item {{ Request::is('contact') ? 'active' : '' }}">
                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Contacto</a>
            </li>
        </ul>
        <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
            <li class="nav-item {{ Request::is('login') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            @if (Route::has('register'))
            <li class="nav-item {{ Request::is('register') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
            @endif
            @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
            @endguest
        </ul>
    </div>
    </div>
</nav>